All_product:
    path:     /readProducts
    defaults: { _controller: SellProductsBundle:product:read }

addProducts:
    path:     /addproduct
    defaults: { _controller: SellProductsBundle:product:add}

deleteProduct:
    path:     /deleteproduct/{id}
    defaults : { _controller : SellProductsBundle:product:delete}

details_products:
    path:    /productsDetails/{id}
    defaults: {_controller : SellProductsBundle:product:details}
shopping_card:
    path:    /shoppingcard
    defaults: { _controller: SellProductsBundle:product:shoppingcard}
updateProduct:
    path:    /updateproduct/{id}
    defaults : { _controller: SellProductsBundle:product:update}
ajax_search:
    path:    /search
    defaults: { _controller: SellProductsBundle:product:search }