<?php

namespace SellProductsBundle\Repository;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends \Doctrine\ORM\EntityRepository
{
}
