<?php

namespace SellProductsBundle\Repository;



use SellProductsBundle\Entity\product;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getInfoPanier()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT pa.id,pa.quantity,pa.prix,pro.name,pro.image from SellProductsBundle:panier pa,SellProductsBundle:product pro
            WHERE pa.produitP=pro.id')
            ->getResult();
    }

    public function  truncateTtablePanier()
    {
        $entityManager = $this->getEntityManager();

        $connection = $entityManager->getConnection();
        $platform   = $connection->getDatabasePlatform();

        $connection->executeUpdate($platform->getTruncateTableSQL('panier', true /* whether to cascade */));

    }

}
