<?php

namespace EventsBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser ($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.name,p.id,p.location,p.prix,p.image,p.quantity,p.description,p.end,p.start FROM EventsBundle:Events p where p.userid=:id'
            )
            ->setParameter('id',$id)
            ->getResult();
    }



}
