<?php

namespace EventsBundle\Repository;

/**
 * ParticiperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticiperRepository extends \Doctrine\ORM\EntityRepository
{


    public function findBychamps ($id,$event)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.champsConfirmation FROM EventsBundle:Participer p , EventsBundle:Events e,AppBundle:User i where p.user=:id and p.eventtP =:event'
            )
            ->setParameter('id',$id)
            ->setParameter('event',$event)

            ->getResult();
    }
    public function findByPari ($id,$event)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM EventsBundle:Participer p , EventsBundle:Events e,AppBundle:User i where p.user=:id and p.eventtP =:event'
            )
            ->setParameter('id',$id)
            ->setParameter('event',$event)

            ->getResult();
    }
}
