<?php

namespace RentProductsBundle\Repository;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentprodRepository extends \Doctrine\ORM\EntityRepository
{
}
