<?php

namespace ForumBundle\Repository;

/**
 * BlogLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
