<?php

namespace ForumBundle\Repository;

/**
 * blogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogsRepository extends \Doctrine\ORM\EntityRepository
{
}
