<?php

namespace PostBundle\Repository;

/**
 * NblikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NblikeRepository extends \Doctrine\ORM\EntityRepository
{
}
