forum_homepage:
    path:     /
    defaults: { _controller: PostBundle:Default:affiche }
addpost :
    path:     /addpost
    defaults: { _controller: PostBundle:Default:addpost }
afficherpost :
    path:     /affiche
    defaults: { _controller: PostBundle:Default:affiche }
details:
        path:     /details/{id}
        defaults: { _controller: PostBundle:Default:details }
edit:
        path:     /edit/{id}
        defaults: { _controller: PostBundle:Default:edit }
delete :
    path:     /delete/{id}
    defaults: { _controller: PostBundle:Default:delete }
likeBlog :
    path:     /likeBlog/{id}
    defaults: { _controller: PostBundle:Default:likeBlog }
Affichermobile :
    path:     /Aff
    defaults: { _controller: PostBundle:Default:affichermobile }
addpostm :
    path:     /addpostM
    defaults: { _controller: PostBundle:Default:addpostM }