<?php

namespace MaintenanceBundle\Repository;

use MaintenanceBundle\Entity\mechanicien;

/**
 * mechanicienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mechanicienRepository extends \Doctrine\ORM\EntityRepository
{


    public function getMechanicienbyPrix()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM MaintenanceBundle:Mechanicien m 
ORDER BY m.prix ASC");
        return $query->getResult();
    }
    public function findByUser ($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.nom,p.id,p.prenom,p.prix,p.experience,p.description,p.mail,p.image FROM MaintenanceBundle:mechanicien p where p.userid=:id'
            )
            ->setParameter('id',$id)
            ->getResult();
    }
}
